// ═══ STORAGE GROUPS ═══
export const STORAGE_GROUPS = [
  { id: 'G1', name: 'Main Cabinet',     icon: '🟩', color: '#0F6E56', shelfDirection: 'fb' },
  { id: 'G2', name: 'Narcotic Safe',    icon: '🔴', color: '#A32D2D', shelfDirection: 'fb' },
  { id: 'G3', name: 'Emergency Cart',   icon: '🚨', color: '#D85A30', shelfDirection: 'fb' },
  { id: 'G4', name: 'Refrigerator',     icon: '🔵', color: '#185FA5', shelfDirection: 'fb' },
  { id: 'G5', name: 'IV Fluid Shelf',   icon: '🟣', color: '#534AB7', shelfDirection: 'fb' },
  { id: 'G6', name: 'Topical Meds',     icon: '🟤', color: '#854F0B', shelfDirection: 'fb' },
  { id: 'G7', name: 'Code8 Box',        icon: '🔶', color: '#D85A30', shelfDirection: 'fb' },
  { id: 'G8', name: 'Extra Stock',      icon: '📦', color: '#5F5E5A', shelfDirection: 'fb' },
]

// ═══ DRUG MASTER — par = จำนวนใน stock ═══
// min = ค่าแจ้งเตือน Low Stock
export const DRUG_MASTER = [
  // ── Emergency Cart ──
  { id:  1, name: 'Cordarone',              unit: 'amp', par:  2, min: 1, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  2, name: '50%MgSO4',               unit: 'amp', par:  4, min: 2, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  3, name: 'Digoxin',                unit: 'amp', par:  1, min: 1, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  4, name: 'Valium',                 unit: 'amp', par:  2, min: 1, groupId: 'G3', highAlert: false, controlled: true,  singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  5, name: 'Adrenaline',             unit: 'amp', par: 30, min:10, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  6, name: 'Adenosine',              unit: 'amp', par:  5, min: 2, groupId: 'G3', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  7, name: 'Norepinephrine',         unit: 'amp', par:  2, min: 1, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  8, name: 'Dopamine',               unit: 'amp', par:  1, min: 1, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id:  9, name: 'Atropine',               unit: 'amp', par:  5, min: 2, groupId: 'G3', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 10, name: '10%Calcium gluconate',   unit: 'amp', par:  2, min: 1, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 11, name: 'Dobutamine',             unit: 'amp', par:  1, min: 1, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 12, name: '7.5%NaHCO3',             unit: 'amp', par:  4, min: 2, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 13, name: '50%Glucose (cart)',       unit: 'amp', par:  1, min: 1, groupId: 'G3', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  // ── Main Cabinet ──
  { id: 14, name: '50%Glucose',             unit: 'amp', par:  1, min: 1, groupId: 'G1', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 15, name: 'Dexa',                   unit: 'amp', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 16, name: 'Berodual',               unit: 'btl', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 17, name: 'Asmasal',                unit: 'btl', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 18, name: 'Hydrocortisone',         unit: 'vial',par:  1, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 19, name: 'CPM',                    unit: 'amp', par:  1, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 20, name: 'Ondansetron',            unit: 'amp', par:  1, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 21, name: 'Plasil',                 unit: 'amp', par:  1, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 22, name: 'Lasix 20mg',             unit: 'amp', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 23, name: 'Lasix 250mg',            unit: 'amp', par:  1, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 24, name: 'Nicardipine 10mg',       unit: 'amp', par:  2, min: 1, groupId: 'G1', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 25, name: 'Hadol',                  unit: 'amp', par:  1, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 26, name: 'Vit K 10mg',             unit: 'amp', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 27, name: 'ASA gr.V',               unit: 'tab', par:  1, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 28, name: 'Transamin',              unit: 'amp', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 29, name: 'Brilinta',               unit: 'tab', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 30, name: 'Isodril 5mg',            unit: 'tab', par:  2, min: 1, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 31, name: 'Plavix',                 unit: 'tab', par:  4, min: 2, groupId: 'G1', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 32, name: 'Dilantin',               unit: 'amp', par:  4, min: 2, groupId: 'G1', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 33, name: 'NTG 50mg',               unit: 'amp', par:  1, min: 1, groupId: 'G1', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  // ── Narcotic Safe ──
  { id: 34, name: 'Morphine',               unit: 'amp', par:  2, min: 1, groupId: 'G2', highAlert: true,  controlled: true,  singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 35, name: 'Pethidine',              unit: 'amp', par:  2, min: 1, groupId: 'G2', highAlert: true,  controlled: true,  singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 36, name: 'Fentanyl',               unit: 'amp', par:  1, min: 1, groupId: 'G2', highAlert: true,  controlled: true,  singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 37, name: 'Domicum',                unit: 'amp', par:  4, min: 2, groupId: 'G2', highAlert: true,  controlled: true,  singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 38, name: 'Propofol',               unit: 'vial',par:  1, min: 1, groupId: 'G2', highAlert: false, controlled: true,  singleStock: false, alertDays: 30, fullDateExp: false },
  // ── IV Fluid Shelf ──
  { id: 39, name: '0.45%NSS 500ml',         unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 40, name: '0.9%NSS 500ml',          unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 41, name: 'D5W 500ml',              unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 42, name: '5%DNSS 1000ml',          unit: 'bag', par:  1, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 43, name: '0.45%NSS 1000ml',        unit: 'bag', par:  1, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 44, name: '5%DN/2 1000ml',          unit: 'bag', par:  1, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 45, name: '0.9%NSS 1000ml',         unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 46, name: '0.9%NSS 100ml',          unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 47, name: 'D5W 100ml',              unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 48, name: '5%Acetar 1000ml',        unit: 'bag', par:  1, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 49, name: '5%DW 1000ml',            unit: 'bag', par:  1, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 50, name: '10%DN/2 1000ml',         unit: 'bag', par:  1, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 51, name: '10%DNSS 1000ml',         unit: 'bag', par:  1, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 52, name: 'LRS 1000ml',             unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 53, name: 'Acetar 1000ml',          unit: 'bag', par:  2, min: 1, groupId: 'G5', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  // ── Refrigerator ──
  { id: 54, name: 'Heparin',                unit: 'vial',par:  1, min: 1, groupId: 'G4', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 55, name: 'Mixtard',                unit: 'vial',par:  1, min: 1, groupId: 'G4', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 56, name: 'NPH',                    unit: 'vial',par:  1, min: 1, groupId: 'G4', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 57, name: 'Humurine-R',             unit: 'vial',par:  1, min: 1, groupId: 'G4', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 58, name: 'Nimbex',                 unit: 'amp', par:  4, min: 2, groupId: 'G4', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 59, name: 'Oxytocin',               unit: 'amp', par:  1, min: 1, groupId: 'G4', highAlert: true,  controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 60, name: '1%XylocainAd',           unit: 'amp', par:  1, min: 1, groupId: 'G4', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 61, name: '2%XylocainAd',           unit: 'amp', par:  1, min: 1, groupId: 'G4', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  // ── Topical Meds ──
  { id: 62, name: 'SWI 1000ml',             unit: 'btl', par:  2, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 63, name: 'SW 1000ml ฝาเกลียว',    unit: 'btl', par:  1, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 64, name: 'NSS 1000ml ฝาเกลียว',   unit: 'btl', par:  1, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 65, name: 'Xylocain jelly',         unit: 'tube',par:  1, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 66, name: 'KY jelly',               unit: 'tube',par:  2, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 67, name: '2%ChlohexACL',           unit: 'btl', par:  2, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 68, name: '1%Xylocain',             unit: 'amp', par:  1, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 69, name: '2%Xylocain',             unit: 'amp', par:  1, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 70, name: 'NSS K&K',                unit: 'btl', par:  2, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  { id: 71, name: 'Betadine',               unit: 'btl', par:  2, min: 1, groupId: 'G6', highAlert: false, controlled: false, singleStock: false, alertDays: 30, fullDateExp: false },
  // ── Code8 Box ──
  { id: 72, name: 'Adrenaline (code)',       unit: 'amp', par: 10, min: 9, groupId: 'G7', highAlert: true,  controlled: false, singleStock: false, alertDays: 10, fullDateExp: false },
  { id: 73, name: '50%MgSO4 (code)',         unit: 'amp', par:  2, min: 1, groupId: 'G7', highAlert: true,  controlled: false, singleStock: false, alertDays: 10, fullDateExp: false },
  { id: 74, name: 'Cordarone (code)',        unit: 'amp', par:  2, min: 1, groupId: 'G7', highAlert: true,  controlled: false, singleStock: false, alertDays: 10, fullDateExp: false },
  { id: 75, name: 'Atropine (code)',         unit: 'amp', par:  5, min: 4, groupId: 'G7', highAlert: false, controlled: false, singleStock: false, alertDays: 10, fullDateExp: false },
  { id: 76, name: 'Dopamine (code)',         unit: 'amp', par:  1, min: 1, groupId: 'G7', highAlert: true,  controlled: false, singleStock: true,  alertDays: 10, fullDateExp: false },
  { id: 77, name: 'Valium (code)',           unit: 'amp', par:  2, min: 1, groupId: 'G7', highAlert: false, controlled: true,  singleStock: false, alertDays: 10, fullDateExp: false },
  { id: 78, name: 'Levophed (code)',         unit: 'amp', par:  2, min: 1, groupId: 'G7', highAlert: true,  controlled: false, singleStock: false, alertDays: 10, fullDateExp: false },
  { id: 79, name: 'Adenosine (code)',        unit: 'vial',par:  5, min: 4, groupId: 'G7', highAlert: false, controlled: false, singleStock: false, alertDays: 10, fullDateExp: false },
  { id: 80, name: '10%Calcium gluconate (code)', unit: 'amp', par: 1, min: 1, groupId: 'G7', highAlert: true, controlled: false, singleStock: true, alertDays: 10, fullDateExp: false },
  { id: 81, name: '7.5%NaHCO3 (code)',      unit: 'amp', par:  4, min: 3, groupId: 'G7', highAlert: true,  controlled: false, singleStock: false, alertDays: 10, fullDateExp: false },
]

// ═══ NURSES ═══
export const DEFAULT_NURSES = [
  'ปิยะวรรณ เกาะเสมด็',
  'ศิริพร มากพงษ์',
  'ชนัญชิดา ค้าขาย',
  'บุษบา บุญยสมภพ',
  'วิกานดา แสนสันเทียะ',
  'ปัทม์พร เลิศนิธิพรชัย',
  'หิรัญรัศมิ์รุทรพันธ์',
  'จันทิมา ชุ่มจิ้งหรีด',
  'วไลวรรณ บรรณสี',
  'ปานกมล โค้วบ้วนอาน',
  'จุไรรัตน์วงศ์อ่อน',
  'จารุวรรณ สุรศัพท์',
  'ภัทธียา เยาวราฤทธิ์',
  'สาวิตรีเกตสุวรรณ์',
  'ละอองดาว แซ่จู',
  'กัญญรัตน์ตาปนานนท์',
  'รวิสรา ศรีสุวรรณ',
  'พิชชานันท์แนวกิจ',
  'อัญชลีจีนนาสา',
  'ฐิตานันท์เพชรล้ำ',
  'ทินภัทร เขียวอ่อน',
  'วิทยา ชุลเฟื้อง',
  'ณัฐพงษ์ทะวีพูล',
  'ผกามาศ กะกุลพิมพ์',
  'ปาริชาต ตั้งทรงเกียรติ',
  'วรปรียา มหิรัณณ์',
  'นารีฟังคำ',
  'วดาพร หวังจิตร์',
  'สุทธิดา บุญประเสริฐ',
  'สุชานรีโกศการิกา',
  'จิณณ์ธิกา ตรัสสรณวาทิน',
  'ณัฐวุฒิบำรุงกิจ',
  'อัจจิมา ห้ามภัย',
  'ศรัญยา โชติพงษ์',
  'ปิยนุช ชุมพร',
  'ณัฐธิดา ศรีสวัสดิ์',
  'ภัทราวดีนิยมศิลป์',
  'ณัฐสุดา นาอุดม',
  'ธนพร สวาฤทธิ์',
  'อิสริยา คุมพวก',
  'ปรียาภรณ์นองเนือง',
]

export const SHIFTS = ['Day Shift (เวรเดย์) 08:00–20:00', 'Night Shift (เวรไนท์) 20:00–08:00']
export const BEDS   = ['ICU-B1','ICU-B2','ICU-B3','ICU-B4','ICU-B6','ICU-B7','ICU-B8','ICU-B9','ICU-B10']
